version: '3'
services:
  redis-server:
    image: 'redis'
  mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_HOST: 10.0.3.4
      MYSQL_DATABASE: flvservice
      MYSQL_USER: admflvbizdev
      MYSQL_PASSWORD: Ch0c0l@teM1lk!
      MYSQL_ROOT_PASSWORD: Ch0c0l@teM1lk!
  node-app:
    restart: always
    build: .
    ports:
     - "3000:3000"


