version: '3'
services:
  redis-server:
    image: 'redis'
    restart: always
  mysql-server:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: flvservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
  node-app:
    restart: always
    build: .
    stdin_open: true
    tty: true
    ports:
     - "3000:3000"
    links: 
      - mysql-server:mysql-server   
  # tests:
  #   restart: always
  #   build: .
  #   command:  ["sudo", "npm", "run", "test"]    


